version: '3.8'

services:
  # PostgreSQL databáze
  postgres:
    image: postgres:16
    container_name: gmap-scrapper-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - scraper

  # API server
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: gmap-scrapper-api
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - NODE_ENV=production
      - PORT=3002
    ports:
      - "3002:3002"
    volumes:
      - ./apps/server:/app/apps/server
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/server/node_modules
    networks:
      - scraper

  # Klientská aplikace
  client:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
    container_name: gmap-scrapper-client
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3002
      - NODE_ENV=production
    ports:
      - "3001:3001"
    volumes:
      - ./apps/client:/app/apps/client
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/client/node_modules
    networks:
      - scraper

volumes:
  postgres-data:
networks:
  scraper:
    driver: bridge
    